language: python
sudo: yes

matrix:
  include:
    - python: 2.7
      env: TOXENV=py27-ansible194
    - python: 2.7
      env: TOXENV=py27-ansible2010

install:
  - pip install tox

script:
  - tox -e travis
