---
# file: dhcp_server/tasks/apparmor.yml
#
# apparmor configuration tasks.
#

- name: apparmor | ensure dhcpd directories are present in the apparmor configuration
  lineinfile:
    dest=/etc/apparmor.d/usr.sbin.dhcpd
    line="  {{ item }},"
    insertbefore='}'
  with_items:
    - "{{ dhcp_server_dir_log }}/** rw"
    - "{{ dhcp_server_dir_conf }}/ r"
    - "{{ dhcp_server_dir_conf }}/** r"
    - "{{ dhcp_server_dir_pid }}/dhcpd.pid rw"
