---
# file: dhcp_server/tasks/configuration.yml
#
# configuration tasks.
#

- name: configuration | ensure integrity of /etc/default/isc-dhcp-server file
  template:
    src=etc/default/isc-dhcp-server.j2
    dest=/etc/default/isc-dhcp-server
    owner=root
    group=root
    mode=0644
  notify: restart dhcp server

- name: configuration | ensure integrity of /etc/dhcp/dhcpd.conf file
  template:
    src=etc/dhcp/dhcpd.conf.j2
    dest=/etc/dhcp/dhcpd.conf
    owner=root
    group=root
    mode=0644
  notify: restart dhcp server
